name: daily-scrape
on:
  schedule:
    - cron: "0 06 * * *"   # 06:00 UTC daily ( ~07:00 Dublin in summer )
  workflow_dispatch: {}     # lets you run it manually from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Chromium + needed system deps in one go
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Run scraper
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TAB: ${{ secrets.SHEET_TAB }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python scrape.py
